server:
  port: 8080
spring:
  application:
    name: java23
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java23?serverTimezone=GMT&useSSL=false
    username: root
    password: '123456'
mybatis-plus:
  mapper-locations:
    classpath*: mapper/*.xml